#!/bin/bash

for cmd in "$@"; do {
  echo "Process \"$cmd\" started";
  $cmd & pid=$!
  PID_LIST+=" $pid";
} done

trap "kill $PID_LIST" SIGINT

echo "Parallel processes have started";
wait $PID_LIST
echo "ok"
echo "All processes have completed";
for pid in $PID_LIST; do kill -9 $pid; done